-- =====================================================
-- SUPABASE MIGRATION: Create User Status Logs Table
-- =====================================================
-- 
-- HOW TO RUN:
-- 1. Go to your Supabase Dashboard → SQL Editor
-- 2. Create a new query
-- 3. Copy and paste the entire content below
-- 4. Click "Run"
--
-- This table will track all user block/unblock actions
-- =====================================================

-- Create the user_status_logs table
CREATE TABLE IF NOT EXISTS user_status_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    action TEXT CHECK (action IN ('blocked', 'unblocked')) NOT NULL,
    reason TEXT,
    admin_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_user_status_logs_user_id ON user_status_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_user_status_logs_admin_id ON user_status_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_user_status_logs_timestamp ON user_status_logs(timestamp DESC);

-- Enable Row Level Security
ALTER TABLE user_status_logs ENABLE ROW LEVEL SECURITY;

-- ✅ Table created successfully!
-- Your block/unblock endpoint will now work correctly.
