-- ============================================================
-- AI-Based Secure File Sharing & Intrusion Detection System
-- Supabase Database Schema
-- 
-- HOW TO USE:
-- 1. Go to your Supabase Dashboard → SQL Editor
-- 2. Paste this entire file and click "Run"
-- 3. All 10 tables will be created with indexes and RLS enabled
-- ============================================================

-- ===================== USERS =====================
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_login TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- ===================== FILES =====================
CREATE TABLE IF NOT EXISTS files (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    encrypted_path TEXT NOT NULL,
    owner_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    size BIGINT,
    upload_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    encryption_key_id BIGINT,
    checksum TEXT
);

CREATE INDEX IF NOT EXISTS idx_files_owner_id ON files(owner_id);
CREATE INDEX IF NOT EXISTS idx_files_upload_time ON files(upload_time DESC);

ALTER TABLE files ENABLE ROW LEVEL SECURITY;

-- ===================== FILE_ACCESS_PERMISSION =====================
CREATE TABLE IF NOT EXISTS file_access_permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT REFERENCES files(file_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    access_type TEXT CHECK (access_type IN ('read', 'write', 'admin'))
);

CREATE INDEX IF NOT EXISTS idx_fap_file_id ON file_access_permission(file_id);
CREATE INDEX IF NOT EXISTS idx_fap_user_id ON file_access_permission(user_id);

ALTER TABLE file_access_permission ENABLE ROW LEVEL SECURITY;

-- ===================== LOGIN_LOGS =====================
CREATE TABLE IF NOT EXISTS login_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    ip_address TEXT,
    login_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    success BOOLEAN
);

CREATE INDEX IF NOT EXISTS idx_login_logs_user_id ON login_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_login_logs_login_time ON login_logs(login_time DESC);

ALTER TABLE login_logs ENABLE ROW LEVEL SECURITY;

-- ===================== ACCESS_LOGS =====================
CREATE TABLE IF NOT EXISTS access_logs (
    access_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    file_id BIGINT REFERENCES files(file_id) ON DELETE CASCADE,
    action TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_access_logs_user_id ON access_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_access_logs_file_id ON access_logs(file_id);
CREATE INDEX IF NOT EXISTS idx_access_logs_timestamp ON access_logs(timestamp DESC);

ALTER TABLE access_logs ENABLE ROW LEVEL SECURITY;

-- ===================== ALERTS =====================
CREATE TABLE IF NOT EXISTS alerts (
    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    alert_type TEXT,
    risk_score FLOAT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT
);

CREATE INDEX IF NOT EXISTS idx_alerts_user_id ON alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at DESC);

ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

-- ===================== ML_ACTIVITY_DATA =====================
CREATE TABLE IF NOT EXISTS ml_activity_data (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    login_hour INTEGER,
    failed_attempts INTEGER,
    file_count INTEGER,
    ip_change_count INTEGER,
    label TEXT
);

CREATE INDEX IF NOT EXISTS idx_ml_activity_user_id ON ml_activity_data(user_id);

ALTER TABLE ml_activity_data ENABLE ROW LEVEL SECURITY;

-- ===================== SESSIONS =====================
CREATE TABLE IF NOT EXISTS sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expiry TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expiry);

ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

-- ===================== AUDIT_TRAIL =====================
CREATE TABLE IF NOT EXISTS audit_trail (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    event TEXT,
    event_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    details TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_trail_user_id ON audit_trail(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_trail_event_time ON audit_trail(event_time DESC);

ALTER TABLE audit_trail ENABLE ROW LEVEL SECURITY;

-- ===================== ADMIN_ACTIONS =====================
CREATE TABLE IF NOT EXISTS admin_actions (
    action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    action TEXT,
    target_user BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admin_actions_admin_id ON admin_actions(admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_actions_timestamp ON admin_actions(timestamp DESC);

ALTER TABLE admin_actions ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- RLS POLICIES (allow all access via service_role key from backend)
-- These policies allow the backend (using the anon key + RLS bypass 
-- via service_role or with proper policies) to operate.
-- For a backend-only pattern, you can use the service_role key which 
-- bypasses RLS, or add permissive policies below.
-- ============================================================

-- Allow full access for authenticated backend operations
-- (adjust these policies based on your security requirements)
-- Using DROP IF EXISTS + CREATE pattern since PostgreSQL 
-- does not support CREATE POLICY IF NOT EXISTS.

DROP POLICY IF EXISTS "Allow all for users" ON users;
CREATE POLICY "Allow all for users" ON users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for files" ON files;
CREATE POLICY "Allow all for files" ON files FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for file_access_permission" ON file_access_permission;
CREATE POLICY "Allow all for file_access_permission" ON file_access_permission FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for login_logs" ON login_logs;
CREATE POLICY "Allow all for login_logs" ON login_logs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for access_logs" ON access_logs;
CREATE POLICY "Allow all for access_logs" ON access_logs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for alerts" ON alerts;
CREATE POLICY "Allow all for alerts" ON alerts FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for ml_activity_data" ON ml_activity_data;
CREATE POLICY "Allow all for ml_activity_data" ON ml_activity_data FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for sessions" ON sessions;
CREATE POLICY "Allow all for sessions" ON sessions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for audit_trail" ON audit_trail;
CREATE POLICY "Allow all for audit_trail" ON audit_trail FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for admin_actions" ON admin_actions;
CREATE POLICY "Allow all for admin_actions" ON admin_actions FOR ALL USING (true) WITH CHECK (true);
